//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnotherOne
{
    using System;
    
    public partial class FillOutGradeTable_Result2
    {
        public string Lname { get; set; }
        public string Fname { get; set; }
        public int Value { get; set; }
        public string ActivityName { get; set; }
    }
}
